import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LazyLoad from 'react-lazyload';
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      头部
      <body className={inter.className}>{children}</body>
      <LazyLoad>
        <Footer/>
      </LazyLoad>
    </html>
  );
}
